package com.buri.srstart.src;

import com.buri.srstart.exceptions.AlreadyRunningException;
import com.buri.srstart.intf.SRCoreIntf;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author bub
 */
public class SRStart extends javax.swing.JFrame {

    private SRCoreIntf core;
    private SRPositioning positioning;
    
    /**
     * Creates new form SRStart
     */
    public SRStart() {
        initComponents();
        initSR();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("sadfsafsafsad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    private void initSR() {
        this.core = new SRCore();
        this.positioning = new SRPositioning();
        
        try {
            positioning.start();
        } catch (AlreadyRunningException ex) {
            Logger.getLogger(SRStart.class.getName()).log(Level.INFO, ex.getMessage(), ex);
        }
    }
}
