package com.buri.srstart.src;

import com.buri.srstart.data.Position;
import com.buri.srstart.exceptions.AlreadyRunningException;
import com.buri.srstart.intf.SRCoreIntf;
import com.buri.srstart.intf.SRDefaults;
import com.buri.srstart.intf.SRSessionIntf;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author bub
 */
public class SRStart extends javax.swing.JFrame {

    private SRCoreIntf core = null;
    private SRSessionIntf session = null;
    private SRPositioning positioning = null;
    private final Runnable timeUpdater;
    private boolean alive;
    
    
    /**
     * Creates new form SRStart
     */
    public SRStart() {
        alive = true;
        initComponents();
        initSR();
        timeUpdater = () -> {
            
            while (alive) {
                if(positioning != null && jLabCurrentTimeData != null) {
                    LocalDateTime currentTime = positioning.getCurrentGPSTime();
                    Position p = positioning.getCurrentPosition();
                    if (currentTime != null) {
                        jLabCurrentTimeData.setText(currentTime.format(DateTimeFormatter.ofPattern(SRDefaults.DATE_TIME_PATTERN)));
                        jLabCurrentTimeData.paintImmediately(jLabCurrentTimeData.getVisibleRect());
                    }
                    if (p != null) {
                        jLabLatitudeData.setText(p.getFormattedLatitude());
                        jLabLatitudeData.paintImmediately(jLabLatitudeData.getVisibleRect());
                        jLabLongitudeData.setText(p.getFormattedLongitude());
                        jLabLongitudeData.paintImmediately(jLabLongitudeData.getVisibleRect());
                    }
                    
                    if (session != null) {
                        int metersToStartLine = session.getMetersToStartLine();
                        labDistance.setText("Distance: " + metersToStartLine + "m");
                        labDistance.paintImmediately(jLabCurrentTimeData.getVisibleRect());
                        
                        LocalDateTime startTime = session.getStartTime();
                        labRaceTime.setText(startTime.format(DateTimeFormatter.ofPattern(SRDefaults.DATE_TIME_PATTERN)));
                        labRaceTime.paintImmediately(jLabCurrentTimeData.getVisibleRect());
                        
                        int suggestionForSpeed = session.getSuggetionForSpeed();
                        //TODO
                        
                        double speed = session.getSpeedInKnots();
                        labSpeed.setText("Speed: " + speed + "kn");
                        labSpeed.paintImmediately(jLabCurrentTimeData.getVisibleRect());
                    }
                }
                try {
                    synchronized (this) {
                        wait(250);   
                    }
                }catch (InterruptedException ex) {
                    Logger.getLogger(SRStart.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        new Thread(timeUpdater).start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabCurrentTimeText = new javax.swing.JLabel();
        jLabCurrentPosText = new javax.swing.JLabel();
        jLabLatitude = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabCurrentTimeData = new javax.swing.JLabel();
        jLabEmpty = new javax.swing.JLabel();
        jLabLatitudeData = new javax.swing.JLabel();
        jLabLongitudeData = new javax.swing.JLabel();
        butNewRace = new javax.swing.JButton();
        butSettings = new javax.swing.JButton();
        racePanel = new javax.swing.JPanel();
        butSync = new javax.swing.JButton();
        butPlusOneSec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labTimeForStart = new javax.swing.JLabel();
        labDistance = new javax.swing.JLabel();
        labRaceTime = new javax.swing.JLabel();
        labSpeed = new javax.swing.JLabel();
        jProgressDecelerate = new javax.swing.JProgressBar();
        jProgressAccelerate = new javax.swing.JProgressBar();
        butStartSess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sail Race Start");
        setName("Sail Race Start"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabCurrentTimeText.setText("Current Time:");

        jLabCurrentPosText.setText("Current Position:");

        jLabLatitude.setText("Latitude:");

        jLabel1.setText("Longitude:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCurrentPosText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabCurrentTimeText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabLatitude, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabCurrentTimeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabCurrentPosText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabLatitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jLabCurrentTimeData.setText("00-00-00   00-00-00");

        jLabEmpty.setText(" ");

        jLabLatitudeData.setText("000000000");

        jLabLongitudeData.setText("000000000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCurrentTimeData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabEmpty)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabLongitudeData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(jLabLatitudeData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabCurrentTimeData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabLatitudeData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabLongitudeData)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        butNewRace.setText("New Race");
        butNewRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNewRaceActionPerformed(evt);
            }
        });

        butSettings.setText("Settings");
        butSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSettingsActionPerformed(evt);
            }
        });

        racePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        butSync.setBackground(new java.awt.Color(51, 255, 51));
        butSync.setText("Sync");

        butPlusOneSec.setText("+1 sec");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Stop");

        labTimeForStart.setText("Start: 12:02:04");

        labDistance.setText("Distance: 30m");

        labRaceTime.setFont(new java.awt.Font("Lato Heavy", 0, 48)); // NOI18N
        labRaceTime.setText("12:00:32");

        labSpeed.setText("Speed: 4.3kn");

        jProgressDecelerate.setOrientation(1);

        jProgressAccelerate.setOrientation(1);

        butStartSess.setBackground(new java.awt.Color(255, 255, 153));
        butStartSess.setText("START");
        butStartSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStartSessActionPerformed(evt);
            }
        });

        jButton2.setText("-1 sec");

        javax.swing.GroupLayout racePanelLayout = new javax.swing.GroupLayout(racePanel);
        racePanel.setLayout(racePanelLayout);
        racePanelLayout.setHorizontalGroup(
            racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(racePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(racePanelLayout.createSequentialGroup()
                        .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labTimeForStart, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(labDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labRaceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, racePanelLayout.createSequentialGroup()
                        .addComponent(butStartSess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressDecelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressAccelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butPlusOneSec, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, racePanelLayout.createSequentialGroup()
                                .addComponent(butSync)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );
        racePanelLayout.setVerticalGroup(
            racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(racePanelLayout.createSequentialGroup()
                .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRaceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(racePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labTimeForStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labDistance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butSync))))
                .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(racePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(butPlusOneSec)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(racePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31))
                    .addGroup(racePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(racePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butStartSess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(racePanelLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jProgressAccelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressDecelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butNewRace, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(racePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSettings)
                    .addComponent(butNewRace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(racePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNewRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNewRaceActionPerformed
        System.out.println("new race");
        session = core.newSession(positioning);
        racePanel.setVisible(true);
    }//GEN-LAST:event_butNewRaceActionPerformed

    private void butSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSettingsActionPerformed
        System.out.println("settings");        // TODO add your handling code here:
    }//GEN-LAST:event_butSettingsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("closing");        // TODO add your handling code here:
        alive = false;
        if(core != null) {core.stopEverything();}
        if (positioning != null) { positioning.close();}
    }//GEN-LAST:event_formWindowClosing

    private void butStartSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStartSessActionPerformed
        session.start();
    }//GEN-LAST:event_butStartSessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butNewRace;
    private javax.swing.JButton butPlusOneSec;
    private javax.swing.JButton butSettings;
    private javax.swing.JButton butStartSess;
    private javax.swing.JButton butSync;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabCurrentPosText;
    private javax.swing.JLabel jLabCurrentTimeData;
    private javax.swing.JLabel jLabCurrentTimeText;
    private javax.swing.JLabel jLabEmpty;
    private javax.swing.JLabel jLabLatitude;
    private javax.swing.JLabel jLabLatitudeData;
    private javax.swing.JLabel jLabLongitudeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressAccelerate;
    private javax.swing.JProgressBar jProgressDecelerate;
    private javax.swing.JLabel labDistance;
    private javax.swing.JLabel labRaceTime;
    private javax.swing.JLabel labSpeed;
    private javax.swing.JLabel labTimeForStart;
    private javax.swing.JPanel racePanel;
    // End of variables declaration//GEN-END:variables


    private void initSR() {
        this.core = new SRCore();
        this.positioning = new SRPositioning();
        
        try {
            positioning.start();
        } catch (AlreadyRunningException ex) {
            Logger.getLogger(SRStart.class.getName()).log(Level.INFO, ex.getMessage(), ex);
        }
       racePanel.setVisible(false);
        
    }
}
